on:
  workflow_run:
    workflows: ["Build, run, test, push"]
    types:
      - completed
  
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      #- uses: actions/checkout@v2
    - name: stop_container
      run: sudo docker stop myapp
      continue-on-error: true
    - name: removes all container
      run: sudo docker rm myapp
      continue-on-error: true
    - name: pull down new image
      run: sudo docker pull rhoofard/liatro_project:latest
    - name: run the docker container
      run: sudo docker run --name myapp -d -p 80:80 rhoofard/liatro_project:latest
