# This is a basic workflow to help you get started with Actions

name: deploy with runners

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: stop all running containers
        run: sudo docker kill $(sudo docker ps -q)
      - name: pull latest image from docker repo
        run: sudo docker pull rhoofard/liatro_project:latest
      - name: start docker container
        run: sudo docker run -p 80:80 rhoofard/liatro_project:latest
