on:
  workflow_run:
    workflows: ["Build, run, test, push"]
    types:
      - completed
  
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      #- uses: actions/checkout@v2
    - name: stops running containers
      run: sudo docker kill $(sudo docker ps -q)
    - name: removes all container
      run: sudo docker rm $(sudo docker ps -a -q)
    - name: pull down new image
      run: sudo docker pull rhoofard/liatro_project:latest
    - name: run the docker container
      run: sudo docker run -p 80:80 rhoofard/liatro_project:latest
