name: Build, run, test, push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      run: docker build --tag docker-node .
    - name: run the docker container
      run: docker run --name nodejsapp -d -p 80:80 docker-node
   # - name: run tests
   #   uses: liatrio/github-actions/apprentice-action@master
      
    - name: Login to docker
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USRNAME}}
        password: ${{secrets.DOCKER_PASS}}
        
    - name: manually pushing image
      run: |
        docker tag docker-node:latest  rhoofard/liatro_project:latest
        docker push rhoofard/liatro_project:latest
