name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      run: docker build --tag docker-node .
    - name: run the docker container
      run: docker run --name nodejsapp -d -p 80:80 docker-node
    - name: run tests
      uses: liatrio/github-actions/apprentice-action@master
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{secrets.DOCKER_USRNAME}}
        password: ${{secrets.DOCKER_PASS}}
    - name: pushing image
      uses: docker/build-push-action@v2
      with:
        push: true
        file: ./Dockerfile
